name: Build Apps

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
  push:
    tags:
      - v*

jobs:
  build-apks-and-linux-app:
    name: Release Apks/LinuxApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      # Android Build
      - name: Build apks
        run: |
          flutter pub get
          flutter build apk --target-platform android-arm64,android-x64 --release --tree-shake-icons
          flutter build apk --target-platform android-arm64,android-x64 --split-per-abi --release --tree-shake-icons
          mkdir -p releases
          mv -f build/app/outputs/flutter-apk/*-release.apk releases
          # Rename app-release.apk to app-universal-release.apk if it exists
          if [ -f releases/app-release.apk ]; then
            mv -f releases/app-release.apk releases/app-universal-release.apk
          fi
      
      # Upload Android Artifacts
      - name: Release APKs to github
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "releases/*-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.TAG || github.ref_name }}

      # Linux Build
      - name: Build linux app
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
          flutter config --enable-linux-desktop
          flutter build linux --release
          cd build/linux/x64/release/bundle
          zip -r linux-release.zip ./
          mv linux-release.zip ../../../../../
      
      # Upload Linux Artifacts
      - name: Release Linux to github
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "linux-release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.TAG || github.ref_name }}

  build-windows-app:
    name: Release Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      # Windows Build
      - name: Build windows
        run: |
          flutter pub get
          flutter config --enable-windows-desktop
          flutter build windows --release --tree-shake-icons
          Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath windows-release.zip -Force
      
      # Upload Windows Artifacts
      - name: Release Windows to github
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "windows-release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.TAG || github.ref_name }}

  build-macos-app:
    name: Release MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Set up xcode
        uses: BoundfoxStudios/action-xcode-select@v1
      
      # macOS Build
      - name: Build macos
        env:
          MACOS_APP_RELEASE_PATH: build/macos/Build/Products/Release
          APP_NAME: longinus_02.app 
        run: |
          flutter config --enable-macos-desktop
          flutter pub get
          flutter build macos --release --tree-shake-icons
          
          # Create DMG using create-dmg (assuming app name is longinus_02.app)
          brew install create-dmg
          cd $MACOS_APP_RELEASE_PATH
          
          # Simple DMG creation
          create-dmg \
            --volname "Longinus Installer" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "$APP_NAME" 200 190 \
            --hide-extension "$APP_NAME" \
            --app-drop-link 600 185 \
            "Longinus.dmg" \
            "$APP_NAME"
            
          cd ../../../../../
          mv $MACOS_APP_RELEASE_PATH/Longinus.dmg macos-release.dmg

      - name: Release Mac to github
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "macos-release.dmg"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.TAG || github.ref_name }}

      # iOS Build (No Signing)
      - name: Build iOS
        run: |
          flutter build ios --release --tree-shake-icons --no-codesign
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload
          zip -r ios-release.ipa Payload
      
      - name: Release iOS to github
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "ios-release.ipa"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.TAG || github.ref_name }}
